name: saher_kit
description: >
  Saher Kit – A modern Flutter project integrating Firebase, local storage, PDF/Excel export, and advanced sharing features.
  Developed by Saher Qaid with support for Arabic and English interfaces.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Core
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.0.3
  uuid: ^3.0.7

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3

  # Local Storage
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5

  # Exports, PDF & Sharing
  pdf: ^3.11.0
  printing: ^5.10.0
  share_plus: ^10.0.2   # ✅ Replaces flutter_share (modern & namespace-safe)
  excel: ^2.1.0
  fl_chart: ^0.65.0
  syncfusion_flutter_xlsio: ^28.1.33
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo1.png
    - assets/fonts/NotoNaskhArabic-Regular.ttf
    - assets/fonts/NotoNaskhArabic-Bold.ttf
  # Optional: add an Arabic font (e.g. NotoNaskhArabic) to improve PDF Arabic rendering.
  # Create folder assets/fonts/ and place TTF files there, then uncomment and edit the section below.
  fonts:
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
        - asset: assets/fonts/NotoNaskhArabic-Bold.ttf

# Launcher icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/images/logo.png
    background_color: "#ffffff"
    theme_color: "#1379FF"
  windows:
    generate: true
    image_path: assets/images/logo.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/images/logo.png
  image_path: assets/images/logo.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/images/logo.png
  remove_alpha_ios: true
  min_sdk_android: 21
