// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmNJnefuynl7U-ulHPcRlPTzU8bs2TAFU',
    appId: '1:818246553741:web:b9cf3d063e8ba59b9392c4',
    messagingSenderId: '818246553741',
    projectId: 'saherkit-35596',
    authDomain: 'saherkit-35596.firebaseapp.com',
    storageBucket: 'saherkit-35596.firebasestorage.app',
    measurementId: 'G-08919N7FNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf3NtAuM8-fWth6S2r_XPYKgIYFKGkTfM',
    appId: '1:818246553741:android:c67338f586f8bd009392c4',
    messagingSenderId: '818246553741',
    projectId: 'saherkit-35596',
    storageBucket: 'saherkit-35596.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnXx2SICEsoGmuFzkkJJE6c8OK16Kda0I',
    appId: '1:818246553741:ios:beca9644775958da9392c4',
    messagingSenderId: '818246553741',
    projectId: 'saherkit-35596',
    storageBucket: 'saherkit-35596.firebasestorage.app',
    iosBundleId: 'com.example.saherKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnXx2SICEsoGmuFzkkJJE6c8OK16Kda0I',
    appId: '1:818246553741:ios:beca9644775958da9392c4',
    messagingSenderId: '818246553741',
    projectId: 'saherkit-35596',
    storageBucket: 'saherkit-35596.firebasestorage.app',
    iosBundleId: 'com.example.saherKit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmNJnefuynl7U-ulHPcRlPTzU8bs2TAFU',
    appId: '1:818246553741:web:85e4f1fe70c075579392c4',
    messagingSenderId: '818246553741',
    projectId: 'saherkit-35596',
    authDomain: 'saherkit-35596.firebaseapp.com',
    storageBucket: 'saherkit-35596.firebasestorage.app',
    measurementId: 'G-P57V940M38',
  );
}
